// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag at 2024-01-01 00:00:00 +0000 UTC
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "email": "support@ai-learning-platform.com"
        },
        "license": {
            "name": "MIT",
            "url": "https://opensource.org/licenses/MIT"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/health": {
            "get": {
                "summary": "Health check",
                "tags": ["System"],
                "produces": ["application/json"],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/api/v1/auth/register": {
            "post": {
                "summary": "Register a new user",
                "tags": ["Authentication"],
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "parameters": [
                    {
                        "in": "body",
                        "name": "request",
                        "description": "Registration data",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.RegisterRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "User created successfully",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "400": {
                        "description": "Invalid input",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "409": {
                        "description": "Username or email already exists",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/api/v1/auth/login": {
            "post": {
                "summary": "Login user",
                "tags": ["Authentication"],
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "parameters": [
                    {
                        "in": "body",
                        "name": "request",
                        "description": "Login credentials",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.LoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Login successful",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "400": {
                        "description": "Invalid input",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "401": {
                        "description": "Invalid credentials",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/api/v1/auth/refresh": {
            "post": {
                "summary": "Refresh JWT token",
                "tags": ["Authentication"],
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "parameters": [
                    {
                        "in": "body",
                        "name": "request",
                        "description": "Current token",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "properties": {
                                "token": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "New token generated",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "401": {
                        "description": "Token expired or invalid",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/api/v1/courses": {
            "get": {
                "summary": "List all courses",
                "tags": ["Courses"],
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "parameters": [
                    {
                        "type": "string",
                        "description": "Filter by category",
                        "name": "category",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by difficulty (beginner, intermediate, advanced)",
                        "name": "difficulty",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "Page number",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 20,
                        "description": "Items per page",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "List of courses with pagination",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "summary": "Create a new course",
                "tags": ["Courses"],
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "parameters": [
                    {
                        "in": "body",
                        "name": "request",
                        "description": "Course data",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.CreateCourseRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Course created successfully",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "400": {
                        "description": "Invalid input",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "403": {
                        "description": "Forbidden (insufficient permissions)",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/api/v1/courses/{course_id}": {
            "get": {
                "summary": "Get course details",
                "tags": ["Courses"],
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "parameters": [
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "Course ID",
                        "name": "course_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Course details",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "400": {
                        "description": "Invalid course ID",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "404": {
                        "description": "Course not found",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "summary": "Update a course",
                "tags": ["Courses"],
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "parameters": [
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "Course ID",
                        "name": "course_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "in": "body",
                        "name": "request",
                        "description": "Updated course data",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.UpdateCourseRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Course updated successfully",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "400": {
                        "description": "Invalid input",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "404": {
                        "description": "Course not found",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "summary": "Delete a course",
                "tags": ["Courses"],
                "produces": ["application/json"],
                "parameters": [
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "Course ID",
                        "name": "course_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "Course deleted successfully"
                    },
                    "404": {
                        "description": "Course not found",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/api/v1/courses/{course_id}/enroll": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "summary": "Enroll in a course",
                "tags": ["Courses"],
                "produces": ["application/json"],
                "parameters": [
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "Course ID",
                        "name": "course_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Enrollment successful",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "404": {
                        "description": "Course not found",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/api/v1/courses/{course_id}/lessons": {
            "get": {
                "summary": "Get course lessons",
                "tags": ["Courses"],
                "produces": ["application/json"],
                "parameters": [
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "Course ID",
                        "name": "course_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "List of lessons",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/api/v1/exercises/{exercise_id}/submit": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "summary": "Submit exercise answer",
                "tags": ["Submissions"],
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "parameters": [
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "Exercise ID",
                        "name": "exercise_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "in": "body",
                        "name": "request",
                        "description": "Submission data",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.SubmitExerciseRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Submission successful",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "400": {
                        "description": "Invalid input",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "429": {
                        "description": "Max attempts reached",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/api/v1/submissions/{submission_id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "summary": "Get submission details",
                "tags": ["Submissions"],
                "produces": ["application/json"],
                "parameters": [
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "Submission ID",
                        "name": "submission_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Submission details",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "404": {
                        "description": "Submission not found",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/api/v1/submissions/{submission_id}/grade": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "summary": "Grade a submission",
                "tags": ["Submissions"],
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "parameters": [
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "Submission ID",
                        "name": "submission_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "in": "body",
                        "name": "request",
                        "description": "Grading data",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.GradeSubmissionRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Submission graded successfully",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "400": {
                        "description": "Invalid input",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "404": {
                        "description": "Submission not found",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "handlers.RegisterRequest": {
            "type": "object",
            "required": ["username", "email", "password"],
            "properties": {
                "username": {
                    "type": "string",
                    "minLength": 3,
                    "maxLength": 50,
                    "example": "john_doe"
                },
                "email": {
                    "type": "string",
                    "format": "email",
                    "example": "john@example.com"
                },
                "password": {
                    "type": "string",
                    "minLength": 8,
                    "example": "SecurePass123"
                },
                "avatar_url": {
                    "type": "string",
                    "example": "https://example.com/avatar.jpg"
                }
            }
        },
        "handlers.LoginRequest": {
            "type": "object",
            "required": ["email", "password"],
            "properties": {
                "email": {
                    "type": "string",
                    "format": "email",
                    "example": "john@example.com"
                },
                "password": {
                    "type": "string",
                    "example": "SecurePass123"
                }
            }
        },
        "handlers.CreateCourseRequest": {
            "type": "object",
            "required": ["title"],
            "properties": {
                "title": {
                    "type": "string",
                    "maxLength": 200,
                    "example": "Introduction to Go Programming"
                },
                "description": {
                    "type": "string",
                    "example": "Learn Go programming from scratch"
                },
                "category": {
                    "type": "string",
                    "example": "Programming"
                },
                "difficulty_level": {
                    "type": "string",
                    "enum": ["beginner", "intermediate", "advanced"],
                    "example": "beginner"
                },
                "estimated_hours": {
                    "type": "integer",
                    "example": 40
                },
                "price": {
                    "type": "number",
                    "example": 99.99
                },
                "thumbnail_url": {
                    "type": "string",
                    "example": "https://example.com/thumb.jpg"
                }
            }
        },
        "handlers.SubmitExerciseRequest": {
            "type": "object",
            "properties": {
                "answer": {
                    "type": "string",
                    "description": "Answer for text-based exercises"
                },
                "code": {
                    "type": "string",
                    "description": "Code for coding exercises"
                },
                "selected_options": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "description": "Selected options for multiple choice"
                }
            }
        },
        "handlers.GradeSubmissionRequest": {
            "type": "object",
            "required": ["score"],
            "properties": {
                "score": {
                    "type": "number",
                    "minimum": 0,
                    "example": 85.5
                },
                "feedback": {
                    "type": "string",
                    "example": "Good work!"
                },
                "is_correct": {
                    "type": "boolean",
                    "example": true
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header",
            "description": "Enter your JWT token in the format: Bearer {token}"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "2.0",
	Host:             "localhost:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{"http", "https"},
	Title:            "AI Learning Platform API",
	Description:      "AI Learning Platform Backend API - Phase 2 Core Features\n\n## Features:\n- User Registration & Login with JWT Authentication\n- Course Management (List, Get, Create, Update, Delete)\n- Assignment Submission & Grading\n- Progress Tracking\n- User Achievements & Notifications",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
